--- #YAML:1.0
name:                Date-Calc
version:             6.3
abstract:            Gregorian calendar date calculations
license:             perl
author:              
    - Steffen Beyer <STBEY@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Bit::Vector:                   7.1
    Carp::Clan:                    6.04
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
